stages:
  - test

test_job:
  image: node:slim
  stage: test
  script:
    - echo "Izvajanje testov..."
    - npm install firebase react react-router-dom resize-observer-polyfill react-testing-library canvas @grpc/grpc-js@latest
    - npm run test