
stages:
  - test
  - build
  - docker-build
  - deploy
  - pages

test_job:
  image: node:slim
  stage: test
  script:
    - echo "Izvajanje testov..."
    - npm install firebase react react-router-dom resize-observer-polyfill react-testing-library canvas @grpc/grpc-js@latest
    - npm run test
  cache:
    
    paths:
      - node_modules/

build_job:
  image: node:slim
  stage: build
  script:
    - echo "Izvajanje gradnje..."
    - npm install firebase react react-router-dom resize-observer-polyfill react-testing-library canvas @grpc/grpc-js@latest
    - export CI=false
    - npm run build
  artifacts:
    paths:
      - build
  cache:
    paths:
      - node_modules/

docker_build_job:
  image: docker:latest
  stage: docker-build
  services:
    - docker:dind
  script:
    - echo "Prijava v DockerHub..."
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
    - echo "Izvajanje gradnje Docker slike..."
    - docker build -t cesi2121/rirsreact .
    - echo "Objava slike na DockerHub..."
    - docker push cesi2121/rirsreact
  only:
    - main

 
deploy_job:
  image: node:slim
  stage: deploy
  enviorments:
    name: fire
  script:
    - echo "Izvajanje namestitve..."
    - npm install -g firebase-tools firebase react react-router-dom resize-observer-polyfill react-testing-library canvas @grpc/grpc-js@latest
    - firebase deploy --token 1//03FTh4yqQF-RjCgYIARAAGAMSNwF-L9Irme9-sTLIWtN-6znaJqqfWWrEkcPpxTecBtjkjSei9M1V_JNYNzSz2AVdzwQRLf4_veM
  only:
    - main

pages:
  stage: pages
  script:
    - mkdir .public
    - cp -r build/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - production