stages:
  - test

test_job:
  image: node:latest
  stage: test
  script:
    - echo "Izvajanje testov..."
    - npm install firebase react react-router-dom resize-observer-polyfill react-testing-library canvas
    - npm run test